import { app, BrowserWindow, Menu, dialog, ipcMain } from 'electron';
import path from 'path';
import fs from 'fs/promises';
import { ConfigSchema } from './shared/types';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

const menuTemplate: (Electron.MenuItemConstructorOptions | Electron.MenuItem)[] = [
  {
    label: 'File',
    submenu: [
      {
        label: 'Open Workspace',
        click: async (menuItem, browserWindow) => {
          if (!browserWindow) return;

          const result = await dialog.showOpenDialog(browserWindow as BrowserWindow, {
            properties: ['openDirectory'],
          });

          if (result.filePaths.length > 0) {
            const workspacePath = result.filePaths[0];
            (browserWindow as BrowserWindow).webContents.send('workspace-opened', workspacePath);
            loadFilestackConfig(workspacePath, browserWindow as BrowserWindow);
          }
        },
      },
      { type: 'separator' },
      { role: 'quit' }
    ]
  },
  {
    label: 'Edit',
    submenu: [
        { role: 'undo' },
        { role: 'redo' },
        { type: 'separator' },
        { role: 'cut' },
        { role: 'copy' },
        { role: 'paste' },
        { role: 'selectAll' }
    ]
  }
];

async function loadFilestackConfig(workspacePath: string, browserWindow: BrowserWindow) {
  try {
    const configPath = path.join(workspacePath, 'filestack.json');
    const fileContent = await fs.readFile(configPath, 'utf-8');
    const config = JSON.parse(fileContent);
    const validationResult = ConfigSchema.safeParse(config);

    if (validationResult.success) {
      browserWindow.webContents.send('config-loaded', validationResult.data.views);
    } else {
      browserWindow.webContents.send('config-error', validationResult.error.message);
    }
  } catch (error) {
    browserWindow.webContents.send('config-error', 'Could not read or parse filestack.json');
  }
}

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = () => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
    },
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`));
  }

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  const menu = Menu.buildFromTemplate(menuTemplate);
  Menu.setApplicationMenu(menu);
  createWindow();
});

ipcMain.on('open-workspace', async (event) => {
  const browserWindow = BrowserWindow.fromWebContents(event.sender);
  if (!browserWindow) return;

  const result = await dialog.showOpenDialog(browserWindow, {
    properties: ['openDirectory'],
  });

  if (result.filePaths.length > 0) {
    const workspacePath = result.filePaths[0];
    browserWindow.webContents.send('workspace-opened', workspacePath);
    loadFilestackConfig(workspacePath, browserWindow);
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
